import type { Preset } from "@/types/animation"

export const ANIMATION_PRESETS: Preset[] = [
  // ── Entrance Presets ────────────────────────────────────────────────────────
  {
    id: "bounce-in",
    name: "Bounce In",
    description: "Playful bounce entrance",
    category: "entrance",
    animationConfig: {
      tweenType: "from",
      y: -100,
      scale: 0.3,
      opacity: 0,
      duration: 0.8,
      ease: "bounce.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.08,
      staggerFrom: "start",
    },
  },
  {
    id: "slide-up-fade",
    name: "Slide Up",
    description: "Clean upward reveal",
    category: "entrance",
    animationConfig: {
      tweenType: "from",
      y: 80,
      opacity: 0,
      duration: 0.5,
      ease: "expo.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.03,
      staggerFrom: "start",
    },
  },
  {
    id: "drop-in",
    name: "Drop In",
    description: "Gravity drop with bounce",
    category: "entrance",
    animationConfig: {
      tweenType: "from",
      y: -200,
      opacity: 0,
      duration: 0.6,
      ease: "bounce.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.05,
      staggerFrom: "start",
    },
  },
  {
    id: "elastic-pop",
    name: "Elastic Pop",
    description: "Springy elastic effect",
    category: "entrance",
    animationConfig: {
      tweenType: "from",
      scale: 0,
      opacity: 0,
      duration: 1.2,
      ease: "elastic.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.06,
      staggerFrom: "center",
    },
  },
  {
    id: "zoom-rotate",
    name: "Zoom Rotate",
    description: "Spiral zoom entrance",
    category: "entrance",
    animationConfig: {
      tweenType: "from",
      scale: 0,
      rotation: 180,
      opacity: 0,
      duration: 0.8,
      ease: "back.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.05,
      staggerFrom: "center",
    },
  },
  {
    id: "cinematic",
    name: "Cinematic",
    description: "Smooth theatrical entrance",
    category: "entrance",
    animationConfig: {
      tweenType: "from",
      y: 30,
      scale: 0.95,
      opacity: 0,
      duration: 1.2,
      ease: "power2.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.07,
      staggerFrom: "center",
    },
  },
  {
    id: "pop-scatter",
    name: "Pop Scatter",
    description: "Explosive pop from center",
    category: "entrance",
    animationConfig: {
      tweenType: "from",
      scale: 0,
      rotation: 25,
      y: 50,
      opacity: 0,
      duration: 0.5,
      ease: "back.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.03,
      staggerFrom: "center",
    },
  },

  // ── 3D Presets ──────────────────────────────────────────────────────────────
  {
    id: "flip-3d",
    name: "3D Flip",
    description: "Dramatic 3D rotation",
    category: "3d",
    animationConfig: {
      tweenType: "from",
      rotationX: -90,
      y: 30,
      scale: 0.8,
      opacity: 0,
      duration: 1,
      ease: "power3.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.05,
      staggerFrom: "start",
    },
  },
  {
    id: "unfold",
    name: "Unfold",
    description: "3D card unfold",
    category: "3d",
    animationConfig: {
      tweenType: "from",
      rotationY: -90,
      x: -30,
      scale: 0.8,
      opacity: 0,
      duration: 0.7,
      ease: "power3.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.04,
      staggerFrom: "start",
    },
  },

  // ── Emphasis Presets ────────────────────────────────────────────────────────
  {
    id: "wave",
    name: "Wave",
    description: "Flowing wave motion",
    category: "emphasis",
    animationConfig: {
      tweenType: "from",
      y: 40,
      rotation: -15,
      scale: 0.9,
      opacity: 0,
      duration: 0.6,
      ease: "sine.inOut",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.04,
      staggerFrom: "start",
    },
  },
  {
    id: "swing-in",
    name: "Swing In",
    description: "Pendulum rotation entrance",
    category: "emphasis",
    animationConfig: {
      tweenType: "from",
      rotation: -45,
      y: 20,
      scale: 0.9,
      opacity: 0,
      duration: 0.9,
      ease: "elastic.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.06,
      staggerFrom: "start",
    },
  },
  {
    id: "blur-in",
    name: "Blur Scale",
    description: "Soft scale with depth",
    category: "emphasis",
    animationConfig: {
      tweenType: "from",
      scale: 1.4,
      opacity: 0,
      duration: 0.7,
      ease: "expo.out",
      filter: { type: "blur", value: 12 },
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.04,
      staggerFrom: "random",
    },
  },

  // ── Text Presets ────────────────────────────────────────────────────────────
  {
    id: "typewriter",
    name: "Typewriter",
    description: "Sequential fast reveal",
    category: "text",
    animationConfig: {
      tweenType: "from",
      opacity: 0,
      duration: 0.05,
      ease: "none",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.04,
      staggerFrom: "start",
    },
  },
  {
    id: "matrix",
    name: "Matrix",
    description: "Digital cascade effect",
    category: "text",
    animationConfig: {
      tweenType: "from",
      y: -60,
      opacity: 0,
      duration: 0.3,
      ease: "power4.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.02,
      staggerFrom: "random",
    },
  },

  // ── Creative Presets ────────────────────────────────────────────────────────
  {
    id: "glitch",
    name: "Glitch",
    description: "Random glitch entrance",
    category: "creative",
    animationConfig: {
      tweenType: "from",
      x: 50,
      skewX: 30,
      scale: 1.2,
      opacity: 0,
      duration: 0.4,
      ease: "power4.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.02,
      staggerFrom: "random",
    },
  },
  {
    id: "whip",
    name: "Whip",
    description: "Snappy horizontal whip",
    category: "creative",
    animationConfig: {
      tweenType: "from",
      x: -120,
      skewX: 45,
      opacity: 0,
      duration: 0.35,
      ease: "expo.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.02,
      staggerFrom: "start",
    },
  },
  {
    id: "scatter",
    name: "Scatter",
    description: "Chaotic random assembly",
    category: "creative",
    animationConfig: {
      tweenType: "from",
      x: 150,
      y: -100,
      rotation: 90,
      scale: 0,
      opacity: 0,
      duration: 0.6,
      ease: "back.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.03,
      staggerFrom: "random",
    },
  },

  // ── Additional Smooth Presets ──────────────────────────────────────────────
  {
    id: "gentle-rise",
    name: "Gentle Rise",
    description: "Subtle slow float upward",
    category: "entrance",
    animationConfig: {
      tweenType: "from",
      y: 24,
      opacity: 0,
      duration: 1,
      ease: "power2.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "words",
      stagger: 0.12,
      staggerFrom: "start",
    },
  },
  {
    id: "cascade",
    name: "Cascade",
    description: "Cascading fall with tilt",
    category: "entrance",
    animationConfig: {
      tweenType: "from",
      y: -40,
      rotation: 8,
      opacity: 0,
      duration: 0.7,
      ease: "power3.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.03,
      staggerFrom: "start",
    },
  },
  {
    id: "silk-slide",
    name: "Silk Slide",
    description: "Smooth horizontal glide",
    category: "entrance",
    animationConfig: {
      tweenType: "from",
      x: -60,
      opacity: 0,
      duration: 0.9,
      ease: "power2.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "words",
      stagger: 0.1,
      staggerFrom: "start",
    },
  },
  {
    id: "focus-in",
    name: "Focus In",
    description: "Blur to sharp reveal",
    category: "emphasis",
    animationConfig: {
      tweenType: "from",
      opacity: 0,
      scale: 1.1,
      duration: 0.8,
      ease: "power2.out",
      filter: { type: "blur", value: 20 },
    },
    splitTextConfig: {
      enabled: true,
      type: "words",
      stagger: 0.15,
      staggerFrom: "start",
    },
  },
  {
    id: "spring-up",
    name: "Spring Up",
    description: "Bouncy vertical spring",
    category: "entrance",
    animationConfig: {
      tweenType: "from",
      y: 60,
      scale: 0.8,
      opacity: 0,
      duration: 1,
      ease: "elastic.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.04,
      staggerFrom: "start",
    },
  },
  {
    id: "fade-scale",
    name: "Fade Scale",
    description: "Minimal scale & fade",
    category: "entrance",
    animationConfig: {
      tweenType: "from",
      scale: 0.92,
      opacity: 0,
      duration: 0.6,
      ease: "power1.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "words",
      stagger: 0.08,
      staggerFrom: "start",
    },
  },
  {
    id: "magnetic",
    name: "Magnetic",
    description: "Pull in from edges",
    category: "creative",
    animationConfig: {
      tweenType: "from",
      x: 100,
      y: -50,
      opacity: 0,
      duration: 0.7,
      ease: "back.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.03,
      staggerFrom: "edges",
    },
  },
  {
    id: "reveal-up",
    name: "Reveal Up",
    description: "Masked upward reveal",
    category: "text",
    animationConfig: {
      tweenType: "from",
      y: 50,
      opacity: 0,
      duration: 0.6,
      ease: "power3.out",
      customStyles: { overflowHidden: true },
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.03,
      staggerFrom: "start",
    },
  },
  {
    id: "spiral-in",
    name: "Spiral In",
    description: "Rotating scale entrance",
    category: "3d",
    animationConfig: {
      tweenType: "from",
      scale: 0,
      rotation: 360,
      rotationX: 45,
      opacity: 0,
      duration: 1,
      ease: "back.out",
    },
    splitTextConfig: {
      enabled: true,
      type: "chars",
      stagger: 0.05,
      staggerFrom: "center",
    },
  },
  {
    id: "curtain",
    name: "Curtain",
    description: "Theatrical line reveal",
    category: "text",
    animationConfig: {
      tweenType: "from",
      y: 40,
      opacity: 0,
      duration: 0.8,
      ease: "power3.out",
      customStyles: { overflowHidden: true },
    },
    splitTextConfig: {
      enabled: true,
      type: "words",
      stagger: 0.1,
      staggerFrom: "start",
    },
  },
]

export const PRESET_CATEGORIES = [
  { id: "entrance", label: "Entrance" },
  { id: "emphasis", label: "Emphasis" },
  { id: "3d", label: "3D" },
  { id: "text", label: "Text" },
  { id: "creative", label: "Creative" },
] as const
